version: "3"

services:
  api:
    build: api
    command: "flask run -h 0.0.0.0 -p 5000"
    environment:
      - FLASK_DEBUG=false
      - FLASK_APP=app/app.py
    ports:
      - "5000:5000"

  client:
    build: client
    ports:
      - "3000:3000"
    links:
      - api
    depends_on:
      - api
