create table sources (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  label text
);

create table attributes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  label text
);

CREATE TABLE sources_attributes (
  id bigint generated by default as identity primary key,
  source_id INTEGER REFERENCES sources(id),
  attribute_id INTEGER REFERENCES attributes(id)
);

CREATE TABLE feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  comment text
);